# FROM nginx:alpine

# WORKDIR /my_app

# COPY books.html ./

# CMD ["nginx", "-g", "daemon off;"]

FROM python:3.10-slim

WORKDIR /my_app

COPY . /app

COPY UI.py ./

COPY requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "--server.port", "8501", "--server.address", "0.0.0.0", "UI.py"]


