FROM postgres:latest

# ENV

WORKDIR /may_app

COPY . /database.sql /docker_enterpoint.d/

COPY requirements.txt ./

COPY database.sql ./

# RUN pip install -r requirements.txt

# CMD ["docker", "main:app", "--reload", "--host", "0.0.0.0",  "--port", "8000"]