FROM postgres:latest

# ENV

WORKDIR /may_app

COPY . /database.sql /docker_enterpoint.d/

COPY requirements.txt ./

COPY database.sql ./

EXPOSE 5432

# RUN pip install -r requirements.txt

# CMD ["docker", "run", "-d", "-p", "5432:5432",  "--name", "postgresdb", "postgres:latest"]